############################################################
# Dockerfile to build Miniconda3 container images
# and install additional packages
############################################################
FROM jupyter/scipy-notebook

USER root
RUN conda install -y pymongo
