############################################################
# Dockerfile to build Miniconda3 container images
# and install additional packages
############################################################
FROM jupyter/scipy-notebook:2c80cf3537ca

USER root
RUN conda install -y pymongo
